email:
  username: truonganhtuan3092@gmail.com
  password: ckkwnmtyalfzhjjv
server:
  servlet:
    session:
      timeout: 30m 
 
spring:          
  application:
    name: cosmetics-shop
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: PhuongTay110903@
    url: jdbc:mysql://localhost:3306/cosmetic?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
# for docker
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: PhuongTay110903
#    url: jdbc:mysql://mysql:3307/cosmetic
#    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 414159991218393
            client-secret: 6244fa3b8d1deb6321c827d629d6583b
            scope: email, public_profile
          google:
            client-id: 1011383604442-n185r37uj9u0bkac7re54ks0urfn4b1i.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

